# Generated by Django 3.1.13 on 2021-08-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210804_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address of the client.', max_length=150, unique=True, verbose_name='Email Address'),
        ),
    ]
