# Generated by Django 3.1.8 on 2021-08-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210826_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('borrower', 'Borrower'), ('investor', 'Investor')], default='borrower', help_text='The account type of the user.', max_length=10, verbose_name='Account type'),
        ),
    ]
