# Generated by Django 3.1.8 on 2021-08-31 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210826_1126'),
        ('locations', '0001_initial'),
        ('kyc_aml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='address_line_1',
            field=models.ForeignKey(help_text="User's address line 1. Must be located in the user's country of residence indicated at the time of registration", on_delete=django.db.models.deletion.PROTECT, to='users.useraddress', verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='city',
            field=models.ForeignKey(help_text="User's city of residence. Must be located in the user's country of residence indicated at the time of registration", on_delete=django.db.models.deletion.PROTECT, to='locations.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='state',
            field=models.ForeignKey(help_text="User's state of residence. Must be located in the user's country of residence indicated at the time of registration", on_delete=django.db.models.deletion.PROTECT, to='locations.state', verbose_name='State/Region'),
        ),
    ]
