# Generated by Django 3.1.8 on 2021-08-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210826_1126'),
        ('kyc_aml', '0002_auto_20210831_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='address_line_2',
            field=models.ForeignKey(blank=True, help_text="User's address line 2. Must be located in the user's country of residence indicated at the time of registration", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.useraddress', verbose_name='Address line 2'),
        ),
    ]
