# Generated by Django 3.1.8 on 2021-08-28 09:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created', verbose_name='Date created')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was modified', verbose_name='Date Modified')),
                ('name', models.CharField(help_text='The name of the team member', max_length=125, verbose_name='Name')),
                ('designation', models.CharField(help_text='Designation/Position of the team member', max_length=125, verbose_name='Designation')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', max_length=225, null=True, verbose_name='LinkedIn handle')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the team member', null=True, upload_to='team', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
