# Generated by Django 3.1.8 on 2021-08-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the team member', max_length=125, verbose_name='Name')),
                ('designation', models.CharField(help_text='Designation/Position of the team member', max_length=125, verbose_name='Designation')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', max_length=225, null=True, verbose_name='LinkedIn handle')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
