# Generated by Django 3.1.8 on 2021-08-27 15:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created', verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was modified', verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the team member', null=True, upload_to='team', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
