# Generated by Django 3.1.8 on 2021-08-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_pages', '0004_auto_20210827_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='uuid',
            new_name='id',
        ),
    ]
